version: '2'

services:
  app:
    image: 'parser-transations:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bycoders
      - SPRING_DATASOURCE_USERNAME=bycoders
      - SPRING_DATASOURCE_PASSWORD=bc1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=bycoders
      - POSTGRES_PASSWORD=bc1234
    ports:
      - "5432:5432"
    volumes:
      - auth-db-volume:/var/lib/postgresql
volumes:
  auth-db-volume: