FROM openjdk:8-jdk-alpine
MAINTAINER bycoders.com
COPY target/parserTransations-0.0.1-SNAPSHOT.jar parserTransations-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/parserTransations-0.0.1-SNAPSHOT.jar"]